/***********************************************************************/
/*                                                                     */
/*  FILE        :IIC_EEPROM.c                                          */
/*  DATE        :Wed, Apr 24, 2019                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

int i = 0, j = 0;
int v = 0;
int cur_pos = 0;
unsigned char LED_pos[] = {0xf, ~0x8, ~0x4, ~0x2};
unsigned char dis_order[] = {0x20, 0x10, 0x1, 0x40, 0x8, 0x2, 0x4, 0x80};
unsigned char data[64 + 2] = {0, 0};
unsigned char address0[2] = {0, 0};
unsigned char address1[2] = {0, 64};
unsigned char rx[128];

int RX_flag = 1;
int TX_flag = 1;
int is_start = 0;

void main(void)
{
	R_PG_Clock_Set();
	R_PG_IO_PORT_Set_P7();
	R_PG_IO_PORT_Set_P9();
	R_PG_IO_PORT_Set_P2();
	R_PG_I2C_Set_C0();
	R_PG_Timer_Start_CMT_U0_C0();
	
	// init status
	R_PG_IO_PORT_Write_P7(0xff);
	R_PG_IO_PORT_Write_P9(0xff);
	R_PG_IO_PORT_Write_P2(0xf);
	
	
	// ---------------------
	//         send
	// ---------------------

	// set page1 data
	for(i = 2; i < 66; ++i){
		data[i] = (i % 2) ? (dis_order[j++]) : (LED_pos[(i - 2) / 16]);
		if(j > 7)
			j = 0;
	}
	// write page1
	R_PG_I2C_MasterSend_C0(0xa0, data, 66);
	while (TX_flag)
		;
	TX_flag = 1;
	for (i = 0; i < 888888; ++i)
		;


	// set page2 data
	j = 7;
	data[1] = 64;
	for(i = 2; i < 66; ++i){
		data[i] = (i % 2) ? (dis_order[j--]) : (LED_pos[3 - (i - 2) / 16]);
		if(j < 0)
			j = 7;
	}
	// write page2
	R_PG_I2C_MasterSend_C0(0xa0, data, 66);
	while (TX_flag)
		;
	TX_flag = 1;
	for (i = 0; i < 888888; i++)
		;


	// ------------------
	//       recive
	// ------------------
	
	// page 1
	R_PG_I2C_MasterSend_C0(0xa0, address0, 2);
	while (TX_flag)
		;
	TX_flag = 1;
	for (i = 0; i < 888888; ++i)
		;
	R_PG_I2C_MasterReceive_C0(0xa1, rx, 64);
	while (RX_flag)
		;
	RX_flag = 1;
	for (i = 0; i < 888888; i++)
		;
		
	// page 2
	R_PG_I2C_MasterSend_C0(0xa0, address1, 2);
	while (TX_flag)
		;
	TX_flag = 1;
	for (i = 0; i < 888888; i++)
		;
	R_PG_I2C_MasterReceive_C0(0xa1, &rx[64], 64);
	while (RX_flag)
		;
	RX_flag = 1;
	for (i = 0; i < 888888; i++)
		;

	i = 0;
	is_start = 1;
}

void Cmt0IntFunc(){
	
	if(!is_start)
		return;
	
	R_PG_IO_PORT_Write_P9(rx[i]);
	R_PG_IO_PORT_Write_P7(~rx[i + 1]);
	
	if(rx[i + 1] == 0x80)
		R_PG_IO_PORT_Write_P2(0);		
	else
		R_PG_IO_PORT_Write_P2(0xf);
		

	i = (i >= 126) ? 0 : (i + 2);
}

void IIC0MasterReFunc(){
	RX_flag = 0;
}

void IIC0MasterTrFunc(){
	TX_flag = 0;
}


#ifdef __cplusplus
void abort(void)
{

}
#endif
