/***********************************************************************/
/*                                                                     */
/*  FILE        :display.c                                             */
/*  DATE        :Thu, Mar 21, 2019                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void get_time();

int i = 0;
int start = 0;
int timeout = 0;
int blink = 0;

int pos = 0;
char mode[] = {0xf, ~0x8, ~0x4, ~0x2};
int min = 0;
int sec = 5;
int time[] = {0, 0, 0, 0};
char number[] = {0x3F, 0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x27, 0x7F, 0x67};


void main(void)
{
	// enable
	R_PG_Clock_Set();
	R_PG_IO_PORT_Set_P1();
	R_PG_ExtInterrupt_Set_IRQ0();
	R_PG_ExtInterrupt_Set_IRQ1();
	R_PG_IO_PORT_Set_P7();
	R_PG_IO_PORT_Set_P9();
	R_PG_Timer_Start_CMT_U0_C0();

	
	R_PG_IO_PORT_Write_P7(0xff);
	R_PG_IO_PORT_Write_P9(0xff);
	
	get_time();
	
	
	while(1){
		
	
		if(!timeout){
			R_PG_IO_PORT_Write_P9(mode[pos]);
			R_PG_IO_PORT_Write_P7(~number[time[pos]]);
			
			if(++i > 1000){
				i = 0;	
				if(++pos >= 4)
					pos = 0;
			}
		}
			
	}
	
}

// add time
void Irq0IntFunc(){
	if(start)
		return;
	if(++sec >= 60){
		sec = 0;
		if(++min > 10)
			min = 0;
	}
	get_time();
}

// start / stop
void Irq1IntFunc(){
	
	if(timeout)
		timeout = 0;	
	else
		start = !start;
}

void Cmt0IntFunc(){
	
	if(start){
		if(--sec < 0){
			sec = 59;
			if(--min < 0){
				min = 0;
				sec = 0;
				start = 0;
				timeout = 1;
			}		
		}	
		get_time();
	}
	else if(timeout){

		R_PG_IO_PORT_Write_P9(blink);
		R_PG_IO_PORT_Write_P7(~number[0]);


		if(blink == 0) 
			blink = 0xff;
		else 
			blink = 0;
			
	}
}

void get_time(){
	time[0] = min / 10;
	time[1] = min % 10;
	time[2] = sec / 10;
	time[3] = sec % 10;
}


#ifdef __cplusplus
void abort(void)
{

}
#endif
